src/web/src/average.ecpp, src/web/src/current.ecpp, src/web/src/datacenter_indicators.ecpp
SUB-PROBLEM: Need to rename src/web/* contents
SOLUTION: Another three files renamed
Does not include rename of
- systemctl wrappers/services
- configuration/state files
`autoreconf -fiv && ./configure && make web-test` works
=> PROBLEM: Repository naming is not updated

Makefile.am, src/agents/legacy_asset/legacy_asset.cc, src/agents/legacy_asset/legacy_asset_server.cc, src/agents/legacy_asset/legacy_asset_server.h
=> Problem: legacy asset server was pushed out of fty-agent

tests/persist/test-topology-power-datacenter.cc, tests/persist/test-topology-power-from.cc, tests/persist/test-topology-power-group.cc
=> Problem: Some tests do not compile with czmq v3.

src/include/str_defs.c, src/include/str_defs.h
Solution: use the same mailbox names
=> Problem: web ui don't get all the answers

src/include/str_defs.c, src/include/str_defs.h, src/web/src/alert_ack.ecpp
Solution: use new mailbox name
=> Problem: alert-list name does not match

src/web/src/alert_list.ecpp
=> Problem: we need to apply new naming policy

Makefile.am, src/agents/legacy_asset/legacy_asset.cc
Solution: configure legacy asset server
=> Problem: autoconfig don't do anything

src/shared/utils_web.cc
Solution: paths corrected
Signed-off-by: Barbora Stepankova <barborastepankova@eaton.com>
=> Problem: incorrect path of config files

src/shared/utils_web.cc
=> Problem: one more path should be corrected

.travis.yml, ci_build.sh, ci_deploy.sh, tools/bios-passwd.in
https://travis-ci.org/jimklimov/fty-rest/builds/194862288 ok
=> Travis passed

src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp
=> Problem: malamute/address for sending emails changed

src/include/defs.h, src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp
Solution: email address defined as new parameter
=> Problem: we need to enter malamute/addres in more suitable way

Makefile.am, src/agents/configure_inform/configure_inform.cc, src/include/fty_asset_uptime_configurator.cc, src/include/fty_asset_uptime_configurator.h
Solution: now, the uptime data are managed by configure_inform
=> Problem: uptime data are managed by autoconfig

.gitignore, .travis.fixsasl, .travis.yml, ci_build.sh, configure.ac, tools/dbinit.h
Hopefully this would help it better find locally built prereqs.
=> configure.ac : accept customized pkgconfigdir, like zproject victims do

src/agents/configure_inform/configure_inform.cc
Solution: when we're updating UPS, send inventory message with new ups
topology for given datacenter
=> Problem: ups layout in all messages (excluding dc)

src/agents/configure_inform/configure_inform.cc, src/include/fty_asset_uptime_configurator.h
=> Problem: aux message does not contain required data

src/shared/ic.c, src/shared/ic.h
=> Problem: We need conversion and transliteration function

src/warranty/warranty-metric.cc, src/web/src/alert_list.ecpp
=> Problem: can't build with recent fty-proto

.travis.yml, tools/astyle-bios, tools/astyle.conf
Some steps closer to getting this code built ok
=> A few build fixes

src/db/inout/importcsv.cc
=> PROBLEM: Space in subtype string

src/web/src/alert_rules.ecpp, src/web/src/alert_rules_list.ecpp
Solution: Add "flexible" type and send request to "fty-alert-flexible"
=> Problem: Can't get list of flexible rules

src/web/src/alert_rules.ecpp, src/web/src/alert_rules_list.ecpp
=> Problem: Won't compile

src/web/src/alert_rules.ecpp
=> Problem: Regex doesn't match multiline case

src/agents/autoconfig/rule_templates/sts-frequency@__device_sts__.rule, src/agents/autoconfig/rule_templates/sts-preferred-source@__device_sts__.rule, src/agents/autoconfig/rule_templates/sts-voltage@__device_sts__.rule
=> Problem: Rules for STS configuration are not present

Makefile.am
Solution: Add them to Makefile
Signed-off-by: Tomas Halman <Tomas@Halman.net>
=> Problem: Rule templates are not installed

src/web/src/info.ecpp
=> Problem: we need to increase timeout

src/web/src/info.ecpp
=> Problem: debug info improvement and correction

src/db/assets/assetr.cc, src/db/assets/assetr.h, src/web/src/asset_GET.ecpp
Solution: ext_name added and id replaced by name
=> [WIP] Problem: we would like to work with asset name and asset ext_name

src/web/src/asset_GET.ecpp
=> Problem: asset_GET does not work

.gitignore
=> Problem: gitignore update needed

src/db/assets/assetr.cc, src/db/assets/assetr.h, src/web/src/asset_DELETE.ecpp
Solution: change it, fix minor issues with unsigned -1 result
=> Problem: We need asset_DELETE to delete by iname

src/web/src/asset_GET.ecpp
Solution: quotation marks added
=> Problem: invalid json error

src/web/src/asset_GET.ecpp
=> Problem: invalid initialization

src/web/src/asset_GET.ecpp
Solution: fixed and unused variables removed
=> Problem: asset_GET still is broken

src/web/src/input_power_chain.ecpp
=> Problem: we would like to use name in rest api call not database id

src/web/src/asset_list.ecpp
=> Problem: we want to use name instead of database id

src/web/src/asset_PUT.ecpp
=> Problem: we don't want to use database id anymore

src/web/src/asset_GET.ecpp, src/web/src/uptime.ecpp
=> Problem: we would like to use name instead of database id

src/db/assets/assetr.cc, src/db/assets/assetr.h
=> Problem: Need get asset name and id if I have asset ext name.

src/web/src/alert_list.ecpp
=> Problem: we don't want to use database id in rest api call

src/db/asset_general.cc, src/db/assets/assetcr.cc, src/db/inout/importcsv.cc
Solution: put them to ext, create simple internal names
=> Problem: Need cvs import with utf-8 names

src/web/src/assets_in.ecpp
Solution: Change ID to name, name to extended attribute "name".
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
=> Problem: We don't want to return DB ID from REST API call "assets".

src/persist/dbhelpers.cc
Solution: add a code to check utf-8 validity instead of using
matgical list of weird characters
=> Problem: is_ok name does not know about utf-8

src/persist/dbhelpers.cc
=> Problem: is_ok_name is wrong

src/web/src/asset_DELETE.ecpp, src/web/src/rack_total.ecpp
=> Problem: REST API does not completelly work

src/db/asset_general.cc, src/db/assets/assetcr.cc, src/db/assets/assetcr.h, src/db/assets/assetr.cc, src/db/inout/importcsv.cc
=> Problem: csv import doesn't work

src/web/src/rack_total.ecpp
Solution: return correct asset name
=> Problem: rack total test is broken

tests/persist/test-asset-crud.cc
=> Problem: Test is failing

src/web/src/alert_list.ecpp
Solution: all alerts are listed
=> Problem: we don't want to die when asset id is empty,

src/db/assets/assetr.cc, src/db/assets/assetr.h, src/db/inout/exportcsv.cc
Solution: assets with new name exported
=> Problem: we need all assets to be exported with unicode name

src/web/src/info.ecpp
=> Problem: fty-info protocol has changed

src/db/assets/assetcr.cc
Solution: Make it from max(id)
=> Problem: Last id returns stange number

src/web/src/asset_POST.ecpp
=> Problem: asset POST return numeric id

src/db/assets/assetcr.cc
Solution: fix it, polish it later
=> Problem: wrong SQL

src/db/assets/assetr.cc
Solution: JOIN the tables, so DB will do the work!
=> Problem: id_to_asset_ext does two SQL queries

src/db/assets/assetr.cc
=> Problem: fty-rest build fails

src/web/src/helpers.cc
=> Problem: Wrong condition for checking invalid characters

src/web/src/location_helpers.cc, src/web/src/topology_location_from.ecpp
=> Problem: we don't want to use db id

src/db/assets/assetcr.cc
Solution: Create random unique name and update it later
=> Problem: Created name is ugly and can have duplicities

src/web/src/topology_location_from.ecpp
Solution: parameter check added
=> Problem: call exits with comm error

src/agents/autoconfig/rule_templates/sts-frequency@__device_sts__.rule, src/agents/autoconfig/rule_templates/sts-preferred-source@__device_sts__.rule, src/agents/autoconfig/rule_templates/sts-voltage@__device_sts__.rule
=> Problem: Rule description is wrong.

src/web/src/datacenter_indicators.ecpp, src/web/src/location_helpers.cc
=> Problem: I forgot to correct one database name.

src/db/inout/importcsv.cc
Solution: ... as UI has been changed to support 4, change the backend
too
=> Problem: power source santization have two power sources max

src/db/inout/importcsv.cc
Revert "Problem: asset POST do not translate location"
This reverts commit bd2b6e44680066b8867c3cbd7bf372a7cae8848f.
=> Problem: REST API does work with database ids in location et all

src/db/assets/assetr.cc, src/web/src/location_helpers.cc
=> Problem: conversion of incorrect variable

src/web/src/asset_GET.ecpp
=> Problem: asset GET not fully converted

src/web/src/alert_list.ecpp
=> Problem: incorrect data type

src/agents/autoconfig/rule_templates/sts-frequency@__device_sts__.rule, src/agents/autoconfig/rule_templates/sts-voltage@__device_sts__.rule
=> Problem: ATS rules should produce only warnings

src/db/inout/importcsv.cc
Solution: Extend sanitization function
=> Problem: Import sanitizing doesn't work for power_source.5+ and groups

src/db/inout/importcsv.cc
=> Problem: condition is wrong

src/db/asset_general.cc
=> Problem: asset POST returns wrong error on name conflict

src/db/inout/importcsv.cc, src/web/src/helpers.cc
=> Problem: Sanitized value is not returned

src/web/src/alert_ack.ecpp
Solution: unicode name not send and id added to json response
=> Problem: Problem: we cannot send unicode name to backend + add id to response

src/db/inout/importcsv.cc
=> Problem: Group names are not sanitized

src/db/inout/importcsv.cc, src/web/src/asset_DELETE.ecpp, src/web/src/average.ecpp, src/web/src/input_power_chain.ecpp
Solution: use element-not-found in all appropriate places
=> Problem: not-found error used badly

src/db/inout/importcsv.cc, src/web/src/topology_location_from.ecpp
=> Problem: Topology location doesn't work

src/db/inout/importcsv.cc
=> Problem: CSV import doesn't work for update

src/web/src/uptime.ecpp
=> Problem: uptime response does not display ext name

src/web/src/asset_GET.ecpp
Solution: return iname as src_id and ext/name as src_name
=> Problem: powers returns db id

src/persist/assetcrud.cc
Solution: If not found in name try to get asset by ext.name
=> Problem: We receive ext.name instead of name

src/db/assets/assetr.cc, src/web/src/average.ecpp, src/web/src/input_power_chain.ecpp
Solution: error message corrected
=>  	Problem: incorrect error message

src/web/src/asset_GET.ecpp
Solution: Fix it.
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
=> Problem: src_name is supposed to be extended name.

src/web/src/asset_GET.ecpp
=> Problem: location_uri uses deprecated asset API format

src/shared/ic.c, src/shared/ic.h
=> Problem: We want asset type (or device subtype) in the name

src/shared/ic.c
=> Problem: Asset type must be sanitized too (rack controller)

src/db/asset_general.cc
Solution: fix declaration and behavior of s_strip
=> Problem: asset code fail to build

src/db/asset_general.cc, src/db/inout/exportcsv.cc, src/shared/utils++.cc, src/shared/utils++.h, src/shared/utils.c, src/shared/utils.h, src/shared/utils_web.h, src/web/src/alert_list.ecpp, src/web/src/asset_GET.ecpp, src/web/src/assets_in.ecpp, src/web/src/input_power_chain.ecpp, src/web/src/location_helpers.cc, src/web/src/topology_location_to.ecpp, src/web/src/topology_power.ecpp, tests/shared/test-log.cc, tests/shared/test-utils.cc
=> Problem: sub_type should be without spaces

src/web/src/alert_ack.ecpp, src/web/src/alert_list.ecpp, src/web/src/asset_GET.ecpp, src/web/src/asset_computed_impl.cc, src/web/src/asset_list.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/getlog_GET.ecpp, src/web/src/info.ecpp, src/web/src/my_profile.ecpp, src/web/src/sysinfo.ecpp, src/web/src/systemctl.ecpp, src/web/src/topology_location_to.ecpp
Solution: drop the whitespaces
=> Problem: ecpp warns about trailing whitespace between tags

src/web/src/average.ecpp
SOLUTION: Change to according to specified template
=> PROBLEM: export csv file name is wrong

src/web/src/rack_total.ecpp
=> Problem: rack total not shown in UI

src/web/src/json.ecpp
=> PROBLEM: Wrong Content-Type

src/db/assets/assetcr.cc, src/web/src/asset_list.ecpp
Solution: fix the few annoying ones
=> Problem: typos in logged messages

src/agents/autoconfig/rule_templates/sts-preferred-source@__device_sts__.rule
=> PROBLEM: (BIOS-3490) Internal ID in alert desc

src/web/src/datacenter_indicators.ecpp, src/web/src/rack_total.ecpp
=> Problem: total power returns 0.0 when data are not available

src/agents/autoconfig/rule_templates/sts-preferred-source@__device_sts__.rule
This reverts commit 92d509507040bcfbed1c4d162ce4e2de843994f9.
=> Revert "PROBLEM: (BIOS-3490) Internal ID in alert desc"

src/db/topology2.cc
Solution: start topology_from from scratch, this is PoC for much smaller
topology call, TODO and how to build is in comments
=> Problem: need to enforce ordering in topology

src/db/topology2.cc
Solution: it'd be hard to do so via SQL, handle that in print function
=> Problem: need to filter the output device types

src/db/topology2.cc
Solution: add order field and ORDER BY clause
=> Problem: toplogy2 don't support ordering (the main feature)

src/db/topology2.cc
Solution: add nonrecursive listing
=> Problem: we would like to set recursive listing to false

src/db/json.cc
=> Problem: we need to have comples json response for topology

src/db/topology2.cc
Solution: add serialization code
=> Problem: need to serialize non-recursive topology

src/db/topology2.cc
Solution: add s_json_recursive, which can format data appropriatelly
=> Problem: need to output recursive topology

src/db/topology2.cc
=> Problem: debug calls left

Makefile.am, src/db/topology2.cc, src/include/topology2.h, src/web/src/topology_location_from2.ecpp, src/web/tntnet.xml
Solution: create new _topology_dev_ namespace for REST API
=> Problem: topology 2 not integrated with the fty-rest

src/db/topology2.cc
=> Problem: asset's name not returned in topology2

src/db/topology2.cc
Solution: start recursion with the kids of from element
=> Problem: recursive topology badly formatted

src/db/topology2.cc
=> Problem: topology does not pass CI test

src/db/topology2.cc
=> Problem: order by order asc

src/db/topology2.cc
Solution: show all upper types
=> Problem: recursive filtering broken

src/web/src/topology_location_from2.ecpp
=> Problem: Parameter 'from' must not be empty

src/web/src/topology_location_from2.ecpp
=> Problem: We need to update topology call v2

src/db/topology2.cc
Solution: return after insert being done
=> Problem: leaf devices not added to NodeMap

src/web/src/topology_location_from2.ecpp
=> Problem: return values are not checked

src/web/src/topology_location_from2.ecpp
=> Problem: rest api call does not work

src/web/src/topology_location_from2.ecpp
=> Problem: parameter 'feed_by' does not work

src/web/src/topology_location_from2.ecpp
Solution: 'from' can be 'none' now
=> Problem: We would like parameter 'from' to have value 'none'

src/web/src/topology_location_from2.ecpp
Solution: parameter restricted
=> Problem: parameter 'filter' can contain only certain values

src/web/src/info.ecpp
=> Problem : fty-info protocol has changed

src/web/src/license_POST.ecpp
=> PROBLEM: Can't see what's wrong

src/db/topology2.cc, src/include/topology2.h, src/web/src/topology_location_from2.ecpp
=> Problem: we need to improve checking of input parameters for rest api call

obs/debian.control, obs/fty-rest.dsc
=> Problem: project now uses upstream compatible zeromq

src/web/src/average.ecpp
Solution: Destroy unused string end_date_rep
=> Problem: Small memory leak

src/include/helpers.h, src/web/src/helpers.cc, src/web/src/systemctl.ecpp
=> PROBLEM: rest api call systemctl.ecpp

src/web/src/systemctl.ecpp
Made a mistake in my last PR
SOLUTION: Fix it.
=> PROBLEM: networking service not restartable

src/include/subprocess.h, src/shared/subprocess.cc, src/web/src/systemctl.ecpp
Solution: move s_output to subprocess module
=> Problem: need to call systemctl from license accept

src/web/src/license_POST.ecpp
=> Problem: fty-rest does not build

src/web/src/license_POST.ecpp
=> Problem: REST API tests fails

src/web/src/helpers.cc, src/web/src/systemctl.ecpp
=> Problem: have notes for future systemctl REST API improvements

src/web/src/my_profile.ecpp
Solution: try-catch added and http_die removed
=> Problem: user cannot log in because database creation was postponed

src/web/src/my_profile.ecpp
Solution: only log message generated
=> Problem: if DB is not available we don't want to die

src/web/src/my_profile.ecpp
=> Problem: one more 'die' left

src/db/topology2.cc, src/include/topology2.h
=> Problem: topology order is not handled well from SQL

src/db/topology2.cc, src/include/topology2.h
=> Problem: ext name order dissapears from system

src/db/topology2.cc
Solution: fix SQL syntax error
=> Problem: rest api tests failing

src/shared/asset_types.cc
=> Problem: some subtypes still contain blank space between words

src/include/asset_types.h, src/shared/asset_types.cc
=> Problem: missing subtype for gpio sensors

src/shared/configure_inform.cc
Solution: Do something what works, even though it makes zero sense.
=> Problem: We put garbage into operation.

src/db/assets/assetr.cc, src/web/src/topology_location_from2.ecpp
=> Problem: Warning and exception should be addressed 

src/web/src/netcfg.ecpp
Solution: Handle it and use resolvconf
=> Problem: We need to handle DNS override

src/web/src/scan_progress.ecpp, src/web/src/scan_run.ecpp, src/web/tntnet.xml
Problem : We need more access and information for discovery scan
Solution:
-progress will return json structure with : the percent, the number of discovered devices (all of them), discovered ups, discovered epdu and discovered sts.
-Add the call of stop_scan for a DELETE on scan_run
-If no range on scan_run POST,  Localscan will be launch
-new error if a scan is currently running or not entirely stopped. 
=> Problem : We need more access and information for discovery scan

src/web/src/netcfg.ecpp
=> Problem : augeas dns-nameservers processing interface is uggly

src/web/src/netcfg.ecpp
=> Problem : fix comma end line missing

src/web/src/netcfg.ecpp
Solution : implement rm to delete dns-nameservers child
=> Problem : empty nameservers array is not supported

src/web/src/scan_run.ecpp
Problem: We need to be able to pass a multiscan on JSON format
=> Problem: We need to be able to pass a multiscan on JSON format

src/web/src/netcfg.ecpp
=> Problem : unset a gateway is not supported

src/web/src/asset_GET.ecpp
=> Problem : asset_tag is not a read_only property

src/web/src/email_vote.ecpp
Solution: Also dump nameservers to /etc/udhcpc/dns
Note that there is a complementary PR in bios-boot -> src/etc/udhcpc.script
for this to take effect
=> [DO NOT MERGE YET] Problem: Need to rework DNS handling for DHCP

src/web/src/alert_list.ecpp, src/web/src/asset_GET.ecpp, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/asset_list.ecpp, src/web/src/assets_in.ecpp, src/web/src/current.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/input_power_chain.ecpp, src/web/src/location_helpers.cc, src/web/src/rack_total.ecpp, src/web/src/topology_location_to.ecpp, src/web/src/topology_power.ecpp
Solution: Wrap all the calls of id_to_name_ext_name.
=> Problem: Database failures are not handled properly.

src/db/inout/importcsv.cc
=> Problem: TestAssetImport is not passing.

Makefile.am
Solution: Makefile.am changed too
=> Problem: rule name changed

src/web/src/license_POST.ecpp
Solution: more logging, connection-test
=> Problem: license accept invisibly fails to start DB sometimes

src/web/src/location_helpers.cc
Solution: Do what is was doing before.
=> Problem: Element_id 0 has special meaning in this case.

src/agents/autoconfig/rule_templates/state-change@__device_sensorgpio__.rule
=> Problem: GPIO port is hard coded

src/agents/autoconfig/rule_templates/state-change@__device_sensorgpio__.rule
=> Problem: gpio rule needs more variables

.gitignore, Makefile.am, src/web/src/conf_scan.ecpp, src/web/src/scan_run.ecpp, src/web/tntnet.xml
Solution: First stab of improvement and completion
=> Problem: Various update and completion needed

src/web/src/conf_scan.ecpp
=> Problem: Malformed scriptlet

src/agents/autoconfig/rule_templates/state-change@__device_sensorgpio__.rule
=> Problem: error message needs to be adjusted

src/agents/autoconfig/rule_templates/pir-motion-detector.state-change@__device_sensorgpio__.rule
=> Problem: rule description is not loaded properly

src/shared/utils_web.cc
=> Problem : fty-discovery.cfg needs to be configured by configure REST_API

src/db/assets/assetr.cc, src/db/assets/assetr.h, src/persist/assetcrud.cc, src/persist/assettopology.cc, src/shared/configure_inform.cc, src/shared/data.cc, src/shared/fty_asset_uptime_configurator.cc
Solution: added 6th level parentage support
=> Problem: connecting GPI sensors to Sensor required 6th level of parentage

.travis.yml
=> Problem: Travis default OS is now Ubuntu Trusty (14)

src/db/topology2.cc, src/shared/configure_inform.cc, src/shared/data.cc
Solution: extended string list to 10 parents, extended loops to 10 levels support
=> Problem: missing support for 10 parent levels

src/db/assets/assetr.cc, src/db/assets/assetr.h, src/web/src/assets_in.ecpp
=> Problem: we need to give the possibility to get device without location

src/db/assets/assetr.cc, src/db/assets/assetr.h, src/web/src/assets_in.ecpp
=> Problem:We need to filter asset list for incomplet asset

src/db/assets/assetd.cc
=> Problem: asset with id 0 is not allowed

src/web/src/add_gpio.ecpp, src/web/src/conf_scan.ecpp, src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp, src/web/src/info.ecpp, src/web/src/list_gpio.ecpp, src/web/src/scan_progress.ecpp, src/web/src/scan_run.ecpp, src/web/src/security_headers.ecpp
-> uuid should be destroyed after usage
-> reduce verbosity of security headers
=> Problem : Fix uuid memory leak 

src/db/asset_general.cc, src/db/asset_general.h, src/db/inout.h, src/db/inout/importcsv.cc, src/include/csv.h, src/shared/csv.cc, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/asset_import.ecpp
=> Problem: We need to add read only field with asset update/create info

src/db/inout/importcsv.cc
Solution: added detection of existence of ID element before trying to access it
=> Problem: asset creation throws an exception without set ID

src/db/inout/importcsv.cc
Solution: Added zuuid to messages
=> Problem: Missing zuuid in mailbox messages

Makefile.am, src/db/inout.h, src/db/inout/importcsv.cc, tests/shared/test-csv.cc, tests/shared/test-csv.cc.rc0_2a.csv, tests/shared/test-csv.cc.rc0_3.csv
Solution: Fixed CSV import, updated resolution rules
=> Problem: CSV import had issues duplicating RC-0 instead of updating it

Makefile.am, src/include/utils_web.h, src/web/src/gpo_action.ecpp, src/web/tntnet.xml
Solution: Implement one (just a wrapper for GPO_INTERACTION MB request).
=> Problem: We need a REST API call for GPO interaction.

src/db/inout/importcsv.cc
Solution: Fixed ASSET_DETAIL command
=> Problem: ASSET_DETAIL mailbox message expects GET command instead of ASSET_DETAIL

src/db/inout/importcsv.cc
Solution: prevent power source being myself
=> Problem: assets may have themselves as a power source

src/db/inout/importcsv.cc, tests/shared/test-csv.cc
Solution: Added debug message for easier RC-0 identification debugging, improved csv import speed
=> Problem: csv import is too slow, and hard to debug in some cases

src/db/inout/importcsv.cc
Solution: removed HW based read-only attributes from CSV import for RC-0
=> Problem: read-only HW based values may be overwritten by CSV import for RC-0, CSV import fails on invalid date format with error in UI

src/include/asset_types.h, src/shared/asset_types.cc
=> Problem: we need new subtype 'gpo'

src/include/utils.h, src/shared/utils.c, tests/shared/test-utils.cc
=> utils: Remove unused code

src/web/src/email_feedback.ecpp
Signed-off-by: Daviet, Nicolas <NicolasDaviet@eaton.com>
=> Problem : crash if mkdtemp return null

src/db/topology2.cc
=> topology2: Fix infinite recursion in NodeMap::feed_by()

src/db/topology2.cc
=> topology2: Initialize the asset_order for the root asset

src/web/src/gpo_action.ecpp
=> Problem: invalid json

src/web/src/gpo_action.ecpp
Application of https://github.com/42ity/fty-rest/pull/337 to master branch
=> Problem: invalid json (in master branch)

src/db/topology2.cc, src/web/src/input_power_chain.ecpp
Solution: set source string to utf8
=> Problem: unicode name is not displayed correctly

src/shared/utils_json.cc
Signed-off-by: Daviet, Nicolas <NicolasDaviet@eaton.com>
=> Problem : incoherent code style

packaging/debian/fty-rest-scripts.install, packaging/redhat/fty-rest.spec, src/Makemodule-local.am
Problem: passwd scripts deliver only symlinks to nowhere
=> Problem: tntnet does not look for shared objects of other components

src/web/src/assets_in.ecpp
Pasting the display name directly is not a good idea. While at it,
reduce duplication between assets_all_container() and
assets_in_container().
=> Use the JSON serializer in the /assets call

.gitignore, Makefile.am, project.xml, src/Makemodule-local.am, src/Makemodule.am, src/fty_rest_classes.h, src/web/src/admin_sse.ecpp, src/web/src/auth_verify.ecpp, src/web/src/find_access_token.ecpp, src/web/src/find_access_token.h, src/web/tntnet.xml
=> Split the token "extraction" to do it before everything else

src/web/src/find_access_token.ecpp
=> Problem: we need to continue after find_access_token.ecpp

src/web/src/find_access_token.ecpp
=> Problem: return DECLINE still not work, need to solve this strange issue

acinclude.m4, src/Makemodule-local.am
Former fix is for #371 ad the other was nearby :)
=> Revive SASLAUTHD_MUX support and real detection of ECPPC/TNTNET bins

src/web/src/hw_capability.ecpp
This allows the UI to change behavior depending on what kind of rackcontroller it is talking to.
=> hw_capability: Return also the type of the rack controller

src/shared/configure_inform.cc
Solution: created directly without asking fty-asset to do it
=> Problem: We need to create uuid directly

src/shared/configure_inform.cc, src/web/src/asset_PUT.ecpp
Solution: Send delete msg when inactivated
=> Problem: We don't want to monitor inactive assets 

src/shared/configure_inform.cc
Solution: ask fty-asset for it
=> Problem: uuid gets corrupted when inseretd to DB

src/shared/fty_asset_uptime_configurator.cc
Solution: monitor only active devices
=> Problem: kpi-power-uptime processes inactive UPSs

src/web/src/config.ecpp
=> Problem: We need to access some config with viewer user

include/shared/asset_types.h, src/shared/asset_types.cc, src/web/src/asset_PUT.ecpp
=> Problem: containers should  not be inactivated

src/db/asset_general.cc
Solution: is forbidden and error raised
=> Problem: rc-0 and containers should not be inactivated by csv import

src/web/src/config.ecpp
=> Revert "Problem: We need to access some config with viewer user"

src/web/src/my_profile.ecpp
=> Problem: We need to get the real timeout on my_profile

src/web/src/my_profile.ecpp
=> Code polish

src/db/asset_general.cc
=> Problem: update of RC-0 by csv import is broken

src/db/asset_general.cc
Solution: fixed - dbid for RC-0 is 1 not 0!
=> Problem: condition with incorrect dbid of RC-0

src/web/src/license_POST.ecpp
=> Problem: error code are not displayed in case of issue

src/db/inout/importcsv.cc, src/shared/csv.cc, src/web/src/current.ecpp, tests/shared/test-csv.cc, tests/web/src/test-helpers.cc
=> Problem: asset name must allow almost all characters

src/shared/utils_json.cc, src/web/src/alert_ack.ecpp
=> Problem: We don't wan't to double "escape" the \ and ".

include/shared/utils_json.h, src/db/inout.h, src/db/inout/exportcsv.cc, src/web/src/assets_in.ecpp
=> [IPMCVG-1970] Problem: we want an asset view as fast as csv export

src/db/assets/assetr.cc, src/web/src/assets_in.ecpp
=> Allow /api/v1/assets without type or subtype

src/db/inout/importcsv.cc
Note: This is the commit I mistakenly pushed to release branch - please merge this to make release branch subset of master again.
=>  Problem: Sometimes we process 'create_mode' sent from UI even though we shouldn't.

src/persist/dbhelpers.cc
Solution: Add PDU and GENSET to respective SQL queries.
=> Problem: limitations don't properly sums up amount of power devices

src/persist/dbhelpers.cc
Fixed licensing limitations considering PDU and GENSET
=> Backporting to 1.4

include/shared/utils_json.h, src/db/assets/assetr.cc, src/db/inout.h, src/db/inout/exportcsv.cc, src/web/src/assets_in.ecpp, src/web/src/rack_total.ecpp
* Fix rack_total : escape the " or \ in the rackNames
* Allow /api/v1/assets without type or subtype
* [IPMCVG-1970] Problem: we want an asset view as fast as csv export
=> backport to 1.4

include/db/dbhelpers.h, src/db/inout/importcsv.cc, src/persist/dbhelpers.cc
Solution: check if active assets are updated, or new activated
=> Problem: active assets couldn't be updated when licensing limitation is hit

src/persist/dbhelpers.cc
Solution: fixed SQL query that caused problems due to improper merge.
=> Problem: unable to re-import CSV with more than 1 row

include/web/src/sse.h, src/web/src/sse.cc
=> Don't spam already published alerts on SSE (1.4)

src/db/inout/importcsv.cc
Solution: added check for non-existing assets (when creating/importing them)
Backport of #481
=> Problem: assets could be created when licensing limitation is hit

include/db/dbhelpers.h, src/db/inout/importcsv.cc, src/persist/dbhelpers.cc
Solutoin: used the other id as ename_to_iname fails on rename
=> Problem: unable to rename active asset when limitation is hit

src/web/src/my_profile.ecpp
Solution: return bool in both cases
=> Problem: my_profile.ecpp returns must_change_pwd as bool(GET)/string(PUT)

src/db/asset_general.cc, src/web/src/asset_DELETE.ecpp
This prevents removing a feed when assets are using it.
=> Don't remove source-linked assets

src/web/src/time.ecpp
(cherry picked from commit ef28c78b1030508905b4789dc785b4f268ddbb7a)
=> Problem : setting manual time should be done after stopping NTP

src/db/inout/exportcsv.cc, src/shared/fty_asset_uptime_configurator.cc, src/web/src/alert_list.ecpp, src/web/src/getlog_GET.ecpp, tests/include/catch.hpp
This PR fixes a few errors and warnings reported by gcc7.
=> Fix build with gcc7

src/web/src/alert_rules.ecpp
=> Problem : POST a new rule doesn't work

src/web/src/config.ecpp
Solution: Use the common cleanup function
=> Problem: Redundant code

src/db/asset_general.cc, src/db/inout/importcsv.cc
it accepts index NOT error code!!!
Solution: error code replaced by index
=> Problem: incorrect use of BiosError,

src/shared/configure_inform.cc, src/web/src/alert_ack.ecpp, src/web/src/alert_list.ecpp, src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/asset_GET.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/sse.cc, src/web/src/uptime.ecpp
=> Problem: MLM_ENDPOINT moved to different library

.gitignore, Makefile.am, project.xml, src/Makemodule-local.am, src/Makemodule.am, src/fty_rest_classes.h, src/shared/configure_inform.cc, src/web/src/alert_ack.ecpp, src/web/src/alert_list.ecpp, src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/alert_templates.ecpp, src/web/src/alert_templates.h, src/web/src/asset_GET.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/sse.cc, src/web/src/uptime.ecpp, src/web/tntnet.xml
GET /api/v1/alerts/templates?type=all
returns
[
{
"name" :"average.humidity@__datacenter__.rule"
"template" : {
"threshold" : {
"rule_name"     :   "average.humidity@__name__",
"rule_desc"     :   "Humidity",
"rule_class"    :   "Humidity in data center",
"rule_hierarchy" :   "environment.humidity.dc",
"target"        :   "average.humidity@__name__",
"element"       :   "__name__",
"values_unit"   :   "%",
"values"        :   [ {"low_warning"   : "40"},
{"low_critical"  : "30"},
{"high_warning"  : "60"},
{"high_critical" : "70"} ],
"results"       :   [
{ "low_warning"   : { "action" : [{ "action": "EMAIL" },{ "action": "SMS" }], "severity" : "WARNING", "description" : "Humidity in datacenter is low" }},
{ "low_critical"  : { …
=> For automation, we need to publish rule templates

src/web/src/alert_templates.ecpp
=> Rework JSon output with cxxtools

src/db/inout/exportcsv.cc
=> beautify may ask extra ressource and cpu which be impactive on huge JSON payload

src/db/inout/importcsv.cc
Solution: update calls that use licensing
=> Problem: licensing was changed to proto-based model

src/web/src/asset_DELETE.ecpp, src/web/src/asset_GET.ecpp, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/assets_in.ecpp, src/web/src/current.ecpp, src/web/src/datacenter_indicators.ecpp
=> Problem: asset_POST: mark strings we need to translate 

src/db/inout/exportcsv.cc, src/web/src/asset_export.ecpp
=> Translation enablement for /asset/export.

src/web/src/alert_list.ecpp, src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/asset_list.ecpp, src/web/src/average.ecpp, src/web/src/config.ecpp, src/web/src/systemctl.ecpp, src/web/src/time.ecpp, src/web/src/uptime.ecpp
=> Problem: computed/average: mark strings for translation

src/web/src/alert_ack.ecpp
=> Translation enablement for /alerts/ack.

src/web/src/netcfg.ecpp
=> Translation enablement for /admin/netcfg(s).

src/web/src/http_proxy.ecpp
=> Translation enablement for /admin/http_proxy.

src/web/src/getlog_GET.ecpp
=> Translation enhablement for /admin/getlog.

src/web/src/admin_iface.ecpp, src/web/src/hw_capability.ecpp, src/web/src/info.ecpp
=> Problem: admin/iface: mark strings for translation

src/web/src/alert_ack.ecpp
Solution: Fix it.
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
=> Problem: Wrong message when alert acknowledge fails.

src/web/src/admin_passwd.ecpp.in
=> Translation enablement for /admin/passwd.

src/web/src/sysinfo.ecpp
=> Translation enablement for /admin/sysinfo.

src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp
=> Translation enablement for /admin/email.

src/web/src/admin_sse.ecpp, src/web/src/sse.cc
=> Translation enablement for SSE.

include/cleanup.h, src/db/asset_general.cc, src/db/topology2.cc, src/persist/assetcrud.cc, src/persist/assettopology.cc, src/persist/monitor.cc, src/persist/persist_error.cc, src/shared/data.cc, src/shared/utilspp.cc, src/web/src/topology_location_from.ecpp, src/web/src/topology_location_from2.ecpp, src/web/src/topology_location_to.ecpp, src/web/src/topology_power.ecpp
=> Problem: topology translations

src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp, src/web/src/location_helpers.cc, src/web/src/rack_total.ecpp, src/web/src/topology_location_to.ecpp
Solution: Update the references.
**********************************************
This PR depends on 42ity/fty-common#65, will require Jenkins redeployment to pass.
=> (S/S) Problem: JSON escape function was moved.

src/shared/csv.cc
Solution: Add them.
Signed-off-by: Your Name <JanaRapava@eaton.com>
=> (S/M) Problem: CSV processing lacks translation macros.

src/web/src/average.ecpp
=> (S/S) Problem: some translation strings are malformed

.gitignore, Makefile.am, project.xml, src/Makemodule-local.am, src/Makemodule.am, src/fty_rest_classes.h, src/web/src/asset_actions_GET.ecpp, src/web/src/asset_actions_GET.h, src/web/src/asset_actions_POST.ecpp, src/web/src/asset_actions_POST.h, src/web/tntnet.xml
This exposes the actor fty-nut-command from fty-nut through the REST API to command ePDUs and other NUT devices.
=> Implement asset actions REST API

src/web/src/sysinfo.ecpp
=> sysinfo typo: retrievEing: fixed (1.5.0)

README.md, include/web/src/sse.h, src/web/src/admin_sse.ecpp, src/web/src/sse.cc
=> Problem: SSE generic message support

src/shared/data.cc
=> (S/S) Fix typos in translated messages

src/shared/data.cc
(cherry picked from commit 4cc6f17a43cff44851b8bea1afa59bf374572a16)
=> Fix typos in translated messages

src/web/src/alert_ack.ecpp
(cherry picked from commit ac5e10a9c5aab214e57ebd23dcfe4538c58a703e)
=> Fix typo in error message.

Makefile.am, builds/check_zproject/ci_build.sh, ci_build.sh, configure.ac, include/fty_rest_library.h, packaging/debian/control, packaging/debian/fty-rest.dsc.obs, packaging/redhat/fty-rest.spec, project.xml, src/Makemodule-local.am, src/libfty_rest.pc.in, src/shared/utils_json.cc, src/web/src/current.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/rack_total.ecpp
=> Get metrics from SHM instead of fty-metric-cache

src/web/src/license.ecpp, src/web/src/sse.cc
=> Problem : fix memory leak

src/web/src/license.ecpp, src/web/src/sse.cc
(cherry picked from commit fbf8836317afd42ac2515d978b1121ca9d0b6d64)
=> [Backport 1.5.0] Problem : fix some memory leaks

src/db/inout/importcsv.cc
=> Problem: CSV import may leak memory on error.

src/web/src/alert_ack.ecpp, src/web/src/alert_list.ecpp, src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/alert_templates.ecpp, src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp, src/web/src/hw_capability.ecpp, src/web/src/scan_progress.ecpp, src/web/src/scan_run.ecpp, src/web/src/uptime.ecpp
Problem : zmsg_popstr is not awlays freed
Solution : use MlmGuard approach
Problem : zpoller is not awlays freed
Solution : use MlmGuard approach
Problem: mlm_client_recvx should free its returned value
solution : fix it
=> Problem : fix memory leak - stage 2

src/db/agentstate/agentstate.cc
Solution: Terminate it correctly.
=> Problem: Data string is incorrectly terminated.

src/web/src/auth_verify.ecpp
=> Problem: We shouldn't mix new and free ().

src/db/inout.h, src/db/inout/exportcsv.cc, src/web/src/asset_export.ecpp, src/web/src/sse.cc, src/web/tntnet.xml
Solution: Add new REST API call which supports that.
***********************************************************************************
This PR has a build dependency on https://github.com/42ity/fty-common-db/pull/35
=> Problem: We can't export specific DC.

src/db/inout/importcsv.cc
=> Problem: We can rename asset to a name which is not unique.

src/db/inout/importcsv.cc
Solution: Disabled RC0 promotion for CSV import
=> [S/S] Problem: RC0 promotion results in RC0 being stolen by imported DC

src/db/inout/importcsv.cc, tests/shared/test-csv.cc
Solution: RC0 ID won't be dropped from CSV when RC0 promotion is disabled
=> [S/S] Problem: RC0 couldn't be updated via CSV import

src/Makemodule-local.am
=> Fix builds on Jenkins.

src/web/src/alert_rules_list.ecpp
Signed-off-by: Jean-Baptiste Boric <Jean-BaptisteBORIC@Eaton.com>
=> Hide CAT_INTERNAL rules from REST API

src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/alert_templates.ecpp
Solution: updated MB format for fty-alert-engine communication
Related PR : https://github.com/42ity/fty-alert-engine/pull/190
=> Problem: inconsitency with fty-alert-engine MB messages 

src/web/src/admin_sse.ecpp, src/web/src/sse.cc
Done
* misc log and comments (sync with etn-ipm2-rest code)
=> Problem: code sync with etn-ipm2-rest repository ( SSE code, related to PQSWMBT-3166 fix)

src/web/src/alert_templates.ecpp
=> Hot fix for template rest request

src/shared/utils_json.cc
=> Update after alert refactoring

src/web/src/netcfg.ecpp
=> Display only active network interfaces.

src/web/src/alert_rules_list.ecpp
=> Fix due to JSON inside JSON

src/web/src/alert_rules_list.ecpp
=> Ensure that payload with error at processing are not impcated

src/web/src/alert_rules_list.ecpp
=> substr take size as second argument and not position

src/web/src/alert_list.ecpp
Solution: ixed list full of commas issue, visual fixes
=> Problem: alert/activelist returns only array of commas

src/db/inout/importcsv.cc
Solution: Simplify these
(cherry picked from commit 40e4156c753114b8ce7d52711ea1d1ee1b03eb6b)
=> Problem: Wrong u_size/u_location msg are too complex (2.0.0)

src/db/inout/importcsv.cc
=> Problem: Wrong u_size/u_location msg are too complex

src/web/src/time.ecpp
Give it a little space... NOT!
=> time.ecpp : automatic reformatting broke a regex inside a string value

src/web/src/add_gpio.ecpp, src/web/src/asset_POST.ecpp
=> Problem: wrong offset causes displaying wrong names

src/db/agentstate/agentstate.cc, src/db/asset_general.cc, src/db/inout/exportcsv.cc, src/db/inout/importcsv.cc, src/db/topology2.cc, src/persist/assetcrud.cc, src/persist/assettopology.cc, src/persist/dbhelpers.cc, src/persist/monitor.cc, src/shared/configure_inform.cc, src/shared/data.cc, src/web/src/admin_sse.ecpp, src/web/src/alert_list.ecpp, src/web/src/asset_computed_impl.cc, src/web/src/asset_counter_GET.ecpp, src/web/src/assets_in.ecpp, src/web/src/average.ecpp, src/web/src/current.ecpp, src/web/src/license_POST.ecpp, src/web/src/sysinfo.ecpp, src/web/src/topology_location_from2.ecpp, tests/persist/test-asset-crud.cc, tests/persist/test-asset-crud1.cc, tests/persist/test-dc-power.cc, tests/persist/test-loadcsv.cc, tests/persist/test-rack-power.cc, tests/persist/test-realdatamonitor.cc
=> Remove DB caching.

src/web/src/systemctl.ecpp
Solution: ... but rather "MANAGE"d -- redefine the string for log to make sense
=> Problem: for audit, systemctl is not "CREATE"d with a POST

src/web/src/getlog_GET.ecpp
Solution: reworked to support tar arch. and journalctl logfile(s) generation
* new emc4j-audit, journald and ALL basenames, code reworked to support generated or archive logfile
=> Problem: getlog REST API - PQSWMBT-3457

src/web/src/getlog_GET.ecpp
Solution:
* restore previous msg to pass non-reg Jenkins tests
=> Problem: fix Jenkins tests

src/web/src/current.ecpp
=> Problem: Power is not part of the Outlets object

src/db/inout/exportcsv.cc
UI request.
Logically depends on https://github.com/42ity/fty-common-db/pull/46
=> Add location_type to detailed asset request

src/web/src/getlog_GET.ecpp
=> Problem: Getlog API, etn-mass-management audit file is missing

src/web/src/asset_DELETE.ecpp
=> Attempt to fix bug when syschronous delete of assets

src/db/inout/importcsv.cc
=> Rework activation of asset during csv import

src/web/src/config.ecpp
=> Clean config REST endpoint (2.1.0)

src/web/src/config.ecpp
Re-applies #695 to pending relelase
=> Backport 2.1.0 config rest (2.1.0)

include/shared/data.h, src/shared/data.cc, src/web/src/asset_DELETE.ecpp
Recursive deletetion of the assets
=> Recursive delete assets

src/shared/data.cc, src/web/tntnet.xml
=> Fixed remove of children

src/web/src/asset_DELETE.ecpp
=> Fixes after review

src/shared/data.cc
=> src/shared/data.cc : fix English wording of a thrown message

src/shared/data.cc, src/web/src/asset_DELETE.ecpp, src/web/tntnet.xml
=> Fixed linked assets deletions

src/web/src/alert_rules_list.ecpp
Fixes ticket IPMVAL-2190, solution approved by UI lead.
=> Filter out CAT_AUTOMATION rules

src/db/inout/exportcsv.cc
This reverts commit 9dfd48a634de976458bd5fcfddb831f5080c90e4.
Per UI request, remove changes from #681. Fixes IPMVAL-2171.
=> Revert "Add location_type to detailed asset request"

tests/include/catch.hpp
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Fix test build

src/web/src/auth_verify.ecpp
Signed-off-by: F.-R. Degott <FrancoisRegisDegott@eaton.com>
=> auth_verify.ecpp improvement

src/web/src/getlog_GET.ecpp
fully tested
* optimize (7z content is no more gzipped), fix log and misc
=> getlog: optimization & fix

src/web/src/scan_progress.ecpp
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Add sensor count in discovery report (PQSWPRG-7881)

src/web/src/alert_rules.ecpp
retry mlm connection with larger timeout
=> IPMVAL-2010: retry if connection failed

src/web/src/getlog_GET.ecpp
* read archive passphrase from json file
=> getlog.ecpp: read archive passphrase from json file

src/web/src/find_access_token.ecpp
=> hotfix: bearer token from cookie

src/web/src/getlog_GET.ecpp
* getlog: add release-details.json in maintenance report
=> PQSWMBT-4819 - getlog: add release-details.json in maintenance report

src/web/src/scan_progress.ecpp
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Update log error message on discovery failure (IPMVAL-2760)

src/web/src/getlog_GET.ecpp
=> PQSWMBT-4736 - getlog: archive rotated logfiles

src/web/src/getlog_GET.ecpp
firmwares.cfg (mass-management firmwares) included in maintenance report
=> PQSWMBT-4875 - add firmwares info in maintenance report

src/web/src/getlog_GET.ecpp, src/web/src/scan_progress.ecpp
To all. Due to branch protection...
Conflicts resolution was done on " release/IPM-2.3.1-fix-conflicts "
and this PR must not be merged (DNM)
=> Release/ipm 2.3.1

ecpp/current.ecpp
=> IPMPROG-325 - current.ecpp reviewed

ecpp/topology_location.ecpp
Signed-off-by: Hlib Yarovyi <HlibYarovyi@eaton.com>
=> Fix order of topology location. 

ecpp/average.ecpp
=> IPMPROG-1488 - improvement
