Makefile.am
Solution: drop relevant make rules
=> Problem: build fails on missing preinstall script

src/agents/autoconfig/fty-autoconfig.cc
=> Problem: fty-autoconfig cannot find the templates directory.

src/web/src/systemctl.ecpp
Solution: allow older service names
=> Problem: third parties fail with fty based image

src/web/src/asset_GET.ecpp
BIOS-3178, UI needs to extend property 'power_devices_in_uri' in output json to include 'sts' as well.
SOLUTION: Implement it
=> PROBLEM: Need to update GET asset/<id>

src/db/asset_general.cc
Solution: do not do strdup just because of iconv interface
=> Problem: memory leak

src/shared/utils_web.cc, src/web/src/rack_total.ecpp
Solution: There is a mixup between macros from <math.h> and templates from <cmath>, so use std::isnan() as recommended In The Net.
=> Problem: GNU C++ on some systems has a problem with isnan()

src/warranty/warranty-metric.cc
=> Problem: warranty metric don't build after fty-proto API change

.gitignore, configure.ac
Solution: use old names, it's not that easy to fix it
Revert "configure.ac / .gitignore : this repo is now fty-rest"
This reverts commit 6ad70b1dd4bb38fcf77f75605d2299a85b53138d.
=> Problem: some services does not work

src/agents/autoconfig/RuleConfigurator.cc
Solution: Send flexible rules to fty-alert-flexible
=> Problem: Rules are send only to alert-engine

obs/debian.rules
Solution: folders removed from obs
=> Problem:  we don't have libbiosapi anymore

src/db/assets/assetr.cc
Solution: Remove NULL assignment, return empty strings in case of exception.
=> Problem: Wrong string initialization, not returned value on exception.

src/web/src/asset_DELETE.ecpp
Solution: don't initialize std::string with 0
=> Problem: exception thrown on asset DELETE

src/db/inout/importcsv.cc
Solution: Use map.at instead of []
=> Problem: We need throw exception if link is not present

src/db/inout/importcsv.cc
Solution: call process_row with santize=true
=> Problem: asset POST do not translate location

src/db/asset_general.cc, src/shared/ic.c, src/shared/ic.h
Solution: transliterate returns NULL, but this case is never handled and
empty name is then forbidden. Return prefix-$unixtime in a case
transliteration fails.
=> Problem: can post fully unicode name

src/web/src/asset_GET.ecpp
Solution: return the correct one
=> Problem: asset GET returns wrong error if not found

Makefile.am, src/db/inout/importcsv.cc, src/shared/data.cc, src/shared/utils++.cc
Solution: finally root out the bugs in source code and recipes, so travis tests for the repo pass green!
Consequence: from now on, red travis results for fty-rest is by 99% chance the fault of recent committers.
=> Problem: fty-rest does not pass travis distcheck

.travis.yml, builds/valgrind/ci_build.sh, ci_build.sh
Solution: reference our fork of czmq branch v3.0.2 (vanilla + our few patches) in ci_build.sh. Impacts mostly just the consistency of Travis and common 42ity/FTY builds (our components' configure.ac should comply either way).
=> Problem: our components use random czmq version

src/db/inout/exportcsv.cc
=> Problem: Groups and logical_asset are exported as it, not name

src/web/tntnet.xml
Solution: characters are allowed too
=> Problem: input_power_chain call accepts  only numerical ids

src/web/src/helpers.cc
Solution: be clever and take a look to ext ["name"] if it does not
match.
=> Problem: some clients passes asset name to REST API

Makefile.am, ci_build.sh, configure.ac
Solution: to avoid confusion if there is a choice of same package variants in the system, ensure usage of the one detected during configure.
This is a "low-hanging fruit" subset of original PR #125 which should be safe to merge already (does not require OBS reconfiguration) since this selection only uses pkg-config data we have and detect for ages.
=> Problem: we do not use available pkgconfig deps metadata when building fty-rest

src/db/inout/importcsv.cc
Solution: allow it, system use generated id now
=> Problem: user cannot rename asset

Makefile.am
Rules templates for sts/ats are missing.
They were accidentally removed in this commit
https://github.com/42ity/fty-rest/commit/78ee60d6bb092655b299cf82adf589b22faab134
SOLUTION: Fix it.
=> PROBLEM: Rule templates missing

src/db/asset_general.cc
Solution: use (type|subtype)-sequence format and do not
pass it through iconv
=> Problem: internal name does not match specification

src/agents/autoconfig/rule_templates/sts-voltage@__device_sts__.rule
Template for rule sts-voltage had unescaped template placeholder \_\_name\_\_.
BIOS-3463
SOLUTION: Fix it.
=> PROBLEM: Invalid json

src/web/src/asset_GET.ecpp
Solution: use utils::strip correctly
=> Problem: asset GET return wrong subtype

src/web/src/average.ecpp
`metric/computed/average` rest api call produces response with old
element id.
SOLUTION: Fix it
=> PROBLEM: rest api call response uses old id

src/db/assets/assetr.cc, src/web/src/alert_list.ecpp, src/web/src/asset_DELETE.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/input_power_chain.ecpp, src/web/src/rack_total.ecpp, src/web/src/topology_power.ecpp
Context: the recently introduced persist::name_to_asset_id() returns an int64_t value which is either "-1" for errors (and/or absent asset), or the uint32_t value of database internal identifier. Some consumers just casted the return value to uint32_t and/or did not check for "-1" returns, and got funny results when the value was actually "-1" for error.
Solution: revise existing calls to the function to use int64_t, check for "-1", and use the rest as before. Also make the code look more consistent by naming the value "dbid" in more places (where it causes just little changes in codebase).
Thanks to @kkathreen for pinpointing in the tediously collected logs where exactly things go south.
=> Problem: use of persist::name_to_asset_id() is inconsistent

src/web/src/alert_list.ecpp
Solution: fail only if checked_asset is not empty
=> Problem: asset parameter is optional

src/web/src/average.ecpp
=> PROBLEM: timestamps in csv header repeated multiple times

src/db/topology2.cc
Solution: prevent that by one smart continue and remove default case
when building topology
=> Problem: from is a part of topology reply

src/db/assets/assetr.cc
Solution: sort the extended attributes at least
=> Problem: exported csv's have random order

src/db/topology2.cc, src/include/topology2.h, src/web/src/topology_location_from2.ecpp
Solution: add topology2_group function to get a vector of groups for
each item, extend Topology for groups, add it to formatting functions
=> Problem: groups are not in topology output

src/db/topology2.cc, src/include/topology2.h, src/web/src/topology_location_from2.ecpp
Solution: write a new SELECT to get this list, add a push_back method
for Topology to simplify inserting of new Item and call the SELECT for
each group added to Topology
=> Problem: recursive topology: group contains all the devices

src/db/topology2.cc
Solution: add such elements to NodeMap, define method add with only one
parameter
=> Problem: HTTP 500 on elements w/o kids

src/db/topology2.cc
Solution: do not filter anything else than devices in this case
=> Problem: feed_by for recursive variant returns only devices

src/include/topology2.h
Solution: fix the Topology.empty method to deal with groups as well
=> Problem: topology with groups is not displayed

src/web/src/topology_location_from2.ecpp, src/web/tntnet.xml
Solution: drop the _topology_dev_ namespace and prepend topology2 as the
first handler for topology/location API point. fallback to older impl
for unlocated elements and to= queries
=> Problem: topology2 is mature enough to be used

src/web/src/topology_location_from2.ecpp
=> Problem: parameter 'from' can have value 'none'

src/web/src/systemctl.ecpp
Solution: try to use simpler way of calling systemctl - it might be that
zloop + czmq + tntnet threads collides together somehow, which is not
fun to debug. The downside is that systemctl is WAY more expensive due
all the systemctl calls it does.
=> Problem: not so extensive use of systemctl call crashes tntnet

src/web/src/systemctl.ecpp
Solution: replace by shared::SubProcess with hand made timeout
=> Problem: s_output does not report things correctly

src/web/src/helpers.cc, src/web/src/license_POST.ecpp
Solution: call fty-db-init systemd unit and read and setup the database password
from the /var/lib/fty/sql directory
=> Problem: need to create a database upon license acceptance

src/web/src/license_POST.ecpp
Solution: call the proper script, move the initialization code to the
script. It's going to be more flexible and easier to change
=> Problem: need to enable and start all DB dependent services

src/include/dbpath.h, src/shared/dbpath.cc, src/web/src/license_POST.ecpp
Solution: add a function dbpath, which is called
* from dbpath.o constructor
* after license is accepted
This way web will have proper credentials for database
=> Problem: database credentials not (re)loaded

src/shared/dbpath.cc, tests/web/src/test-helpers.cc
Solution: don't use C++ std::string and __attribute__((constructor)) at
the same time. They have an alergy on them.
=> Problem: unit tests and webserver segfaults

obs/debian.rules
=> Problem in debian.rules : should use /etc not /usr/etc for sysconfdir

src/web/src/helpers.cc, src/web/src/json.ecpp
Update the filter of services that our REST API allows to manipulate, and a couple of typo fixes.
=> systemctl via helpers.cc : support fty-discovery and fty-sensor-gpio

src/include/asset_types.h
=> Problem: incorrect order in enum for sensorgpio

src/include/dbpath.h, src/shared/dbpath.cc, src/shared/log.c, src/web/src/license_POST.ecpp, tests/shared/test-log.cc
Sometime, when accepting the licence, tntnet fail to connect to DB because of bad credentials.
To investigate this issue
- add [pid.thead_id] in our log
- add info log "Updating db url with DB_USER=" 
- force read bios-db-rw file even if it already exist
=> Problem : I want more log when new db credentials are set

src/shared/utils_web.cc
X-Eaton-IPC-image-version and others are missing.
analyze :  X-Eaton-IPC-machine-id ended with a bad return character.
Solution : remove useless machine-id
=> Problem : several headers are not sent by email

src/shared/utils_web.cc
Solution: pass the hardware uuid from envvars to the newly introduced header "X-Eaton-IPC-hardware-uuid"; keep the uuid of email in mis-named "X-Eaton-IPC-uuid" header as it was
See also https://github.com/42ity/fty-core/pull/142
=> Problem: UUID sent over mail is random

src/shared/log.c, src/web/src/alert_ack.ecpp, src/web/src/alert_list.ecpp, src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/asset_DELETE.ecpp, src/web/src/asset_GET.ecpp, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/asset_import.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/uptime.ecpp, tests/shared/test-log.cc
Solution: add headers to files that use it
=> Problem: warnings that getpid() is undefined

src/include/log.h, src/shared/log.c
Solution: change function signature
=> Problem: unsigned long is not always uint64_t

src/include/log.h, src/include/utils_web.h, src/shared/ic.c, src/shared/log.c, src/shared/tntmlm.cc, src/shared/utils_web.cc, src/warranty/warranty-metric.cc, src/web/src/alert_ack.ecpp, src/web/src/alert_list.ecpp, src/web/src/alert_rules.ecpp, src/web/src/alert_rules_detail.ecpp, src/web/src/alert_rules_list.ecpp, src/web/src/asset_DELETE.ecpp, src/web/src/asset_GET.ecpp, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/asset_import.ecpp, src/web/src/datacenter_indicators.ecpp, src/web/src/uptime.ecpp, tests/shared/test-log.cc
Solution: if we have both pThread ID and kernel LWP ID, and they are different, use them in logging as well as in malamute client self-identification (where REST API talks to other components). 
Also took the chance at refactoring the complexity to be in one place, and the leaf code to look simpler.
=> Problem: debugging REST API is easier with all process/thread IDs at hand

src/include/subprocess.h, src/shared/subprocess.cc
Make sure that whenever we close one of the pipe ends, we set it to
PIPE_DEFAULT to avoid closing it again in the destructor. Otherwise, we
could race with a different thread that calls open() or socket()
in-between and gets assigned the same file descriptor.
=> subprocess: Do not close the same file descriptor twice

src/db/topology2.cc, src/include/topology2.h
Treat asset_order as int and sort it accordingly. Fixes BIOS-4241.
=> Sort assets numerically

src/shared/fty_asset_uptime_configurator.cc
Solution: UPS names in datacenter inventory messages are mangled.
That's because c_str() string reference we store goes out of scope immediately,
so we need to store duplicated reference instead.
=> Problem: Agent fty-kpi-power-uptime cannot match UPSes to datacenters.

Makefile.am, src/web/src/security_removeheaders.ecpp, src/web/tntnet.xml
Cache-Control and Pragma HTTP headers does not allow IE to download well font files resource on F5 or C^+F5  button refresh.
Solution : implement a new tntnet servlet "security_removeheaders" witch remove specific HTTP header for specific url mapping.
=> Problem: font files with Cache-Control HTTP header defined break IE

src/include/utils_web.h
String literals are not guaranteed to be merged by the compiler, so
the result of "foo" == "foo" is undefined and thus not a constexpr.
Older gcc did not catch this, but gcc7 now rightfully errors out. As a
band-aid, change it to use strcmp(), which is not required by the
standard to be a constexpr for string constants, but it is a constexpr
with gcc. The proper fix would be to use an enum for error codes instead
of strings.
=> Fix constexpr error in utils_web.h

.gitignore, src/shared/utils_json.cc
Solution : 
For a new rack, the sse make a call to fty-metric-cache, but if fty-metric-cache does not known this new asset, it return result = null.
So add a test if result from metric-cache is null or not.
=> Probleme : rack asset creation broken

src/web/src/admin_sse.ecpp, src/web/src/json.ecpp
Our version of tntnet goes nuts if the same header is set twice:
HTTP/1.1 200 OK
Date: Mon, 26 Feb 2018 12:16:35 GMT
Server: Tntnet/2.2.1
Pragma: Options:
nosniff X-XSS-Protectio
nosniff X-XSS-Protection:
1 X-Auth-Token-Presented:
"VtwMNU0z2O1_HZaEsx-BxUT0tZDTgVO6Z5a6yzqsjyUseZPTaMGABfUy" X-Auth-Verify:
access_auth_le
To work around this, skip the SSE servlet in json.ecpp and do not set
the Cache-Control header twice. After this, the headers are correct and
SSE works with Firefox:
HTTP/1.1 200 OK
Date: Mon, 26 Feb 2018 13:53:49 GMT
Server: Tntnet/2.2.1
Cache-Control: no-store
Pragma: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1
X-Auth-Token-Presented: "-AJt-WTVFTnqhzl0XWU9OUuHpr5_UxeZtMUsliL-O5rSaorup3JJX_GH"
X-Auth-Verify: access_auth_level="3"
Content-Type: …
=> Fix response headers for SSE

packaging/debian/fty-rest-scripts.install
Use paths to "libexec" scripts hardcoded in Makemodule-local
=> fty-rest-scripts.install : revert to single-layered paths to "libexec" scripts

src/db/inout/importcsv.cc
While the field contains the hostname initially, the user can change it
at any time, breaking subsequent cvs export & import.
=> importcsv: Do not check the "name" field of rackcontroller-0

src/db/inout/importcsv.cc
This actually breaks cases which were previously working. A more
thorough fix is needed.
This reverts commit e81d45865e585302c4afcf4b9ae10c150013b52a.
=> Revert "importcsv: Do not check the "name" field of rackcontroller-0"

src/web/src/alert_list.ecpp
fty-alert-engine may send stale entries in the alert list. While this is
probably a bug in the agent, the fty-rest code is attempting to handle
this. It however fails to advance to the next frame if such entry is
encountered. This fixes commit f1c566744224 ("Rebase").
=> Fix a regression in /alerts/activelist

src/Makemodule-local.am
In the end, the `:=` assignment did not make the warning go away, but at least it more clearly passes our intention to future-us (and other developers).
=> Small clean-up for bios-csv recipe

src/web/src/sse.cc
Send a SSE notification if an autodiscovered device (i.e. without location) gets deleted.
=> Fix SSE on autodiscovered device deletion

src/web/src/http_proxy.ecpp
Solution: Don't fail on empty HTTP proxy
=> Problem: HTTP proxy can also be empty

src/Makemodule-local.am
Avoid this confusing coexistance of log lines while they are from two targets processed in parallel (and ending up in a race condition, using a directory not yet made):
````
[  801s] mkdir -p "/usr/src/packages/BUILD/debian/tmp/usr/libexec/fty-rest" && \
[  801s]     mv -f "/usr/src/packages/BUILD/debian/tmp/usr/bin/bios-csv" "/usr/src/packages/BUILD/debian/tmp/usr/libexec/fty-rest/"
[  801s] if test x"/usr/lib/arm-linux-gnueabihf/fty-rest" != x"/usr/libexec/fty-rest" ; then \
[  801s]     for F in tools/bios-passwd tools/testpass.sh ; do \
[  801s]         F="`basename "$F"`"; \
[  801s]         ln -fsr "/usr/src/packages/BUILD/debian/tmp/usr/lib/arm-linux-gnueabihf/fty-rest/$F" "/usr/src/packages/BUILD/debian/tmp/usr/libexec/fty-rest/" ; \
[  801s]     done ; \
[  801s] fi
[  801s] ln: …
```
=> src/Makemodule-local.am : ensure that bios-passwd gets installed

src/db/inout/importcsv.cc
Solution: Add these part of the licensing tier enforcement
=> Problem: Genset, PDU and Feed should also be enforced

src/web/src/rack_total.ecpp
=> Fix rack_total : escape the " or \ in the rackNames

include/shared/configure_inform.h, src/shared/configure_inform.cc, src/web/src/asset_PUT.ecpp, src/web/src/sse.cc
This is a stopgap to prevent items in the UI from disappearing whenever a nonactive asset is modified.
**To be properly fixed later.**
=> Hack around fake DELETE asset messages for SSE

include/web/src/sse.h, src/web/src/sse.cc
Unlike the streams, the SSE doesn't have a TTL concept, so republishing identical alerts is counter-productive.
=> Don't spam already published alerts on SSE

include/db/dbhelpers.h, src/db/inout/importcsv.cc, src/persist/dbhelpers.cc
Solutoin: used the other id as ename_to_iname fails on rename
Backport of #483
=> Problem: unable to rename active asset when limitation is hit

src/web/src/license_POST.ecpp
Follow up for #487 with an active check of DB-related services in the system, if the `start-db-services` script initially timed out.
=> Problem: check if database engine and/or schema are ok after timed-out script

include/shared/subprocess.h, src/shared/subprocess.cc
Solution: have hardkill() for original terminate() job, and terminate() children gracefully
Practical use-case: child processes like `start-db-services` currently leave no trace if aborted by timeout, despite all error-handling and traps set up in the script. A `SIGTERM` should at least let the script squeak before it dies.
=> Problem: subprocess termination is too ungraceful

src/db/asset_general.cc, src/web/src/asset_DELETE.ecpp
This prevents removing a feed when assets are using it.
=> Don't remove source-linked assets (1.4)

src/shared/utils_json.cc
Depends on 42ity/fty-alert-list#44 to be effective.
=> Get alert timestamp from aux.ctime

src/shared/utils_json.cc
Depends on 42ity/fty-alert-list#45 to be effective.
=> Get alert timestamp from aux.ctime (1.4)

src/db/asset_general.cc
This lets the CI override the last datacenter deletion check through environment variables. Tested by adding `FTY_OVERRIDE_LAST_DC_DELETION_CHECK=y` to `/etc/default/fty` and restarting tntnet.
=> Introduce override flag for last DC deletion check

Jenkinsfile, project.xml
MAYBE adding both a big timeout and removal of builds that *still* fail is a bit of oxymoron... but at least CI disk space will be safer...
=> Jenkinsfile support for cleanup of failed builds

include/db/dbhelpers.h, include/shared/configure_inform.h, src/db/inout.h
Solution: Rely on definition in fty-common-db, update includes.
=> Problem: Build fails because of duplicate definition.

src/web/src/sysinfo.ecpp
* Handle errors more gracefully
* Log more details to help figure out the causes in the OS?
* (TEMPORARY?) Return the error details into JSON output so we can see it in e.g. CI logs, now that the call itself should never fail due to these issues
=>  Problem: sysinfo.ecpp sometimes fails dpkg callouts

src/db/asset_general.cc
Solution: Make functions in asset_general return error code as errtype, as DB insert functions do now.
=> Problem: REST API tests get incorrect error code.

packaging/redhat/fty-rest.spec
Part of making our *-rest components packaging follow the same pattern, usable with tntnet in deploy-only packaging.
=> Fix packaging of shared objects into main package so tntnet finds them

src/db/inout/importcsv.cc
Solution: Use messages expected by CI.
=> Problem: Tests fail.

src/web/tntnet.xml
Make sure our REST API clients (CI tests, Web-GUI, etc.) only use non-logged POST requests for logging in.
=> tntnet.xml : forbid to GET oauth tokens

src/web/src/time.ecpp
Solution: If the REST API call takes too long, it tries to add the runtime in seconds to the time specified by the user. This did not work before because int64_t has to be explicitly converted to string.
=> (S/M) Problem: Manual setting of time sometimes fails.

src/db/inout/importcsv.cc
Solution: stop ignoring first message in the limitation bundle (also fixed memleak).
=> Problem: licensing limitation max active power nodes is ignored

src/Makemodule-local.am
Solution: Reorder compPath entries properly.
=> Problem: Directory /usr/lib/bios/ is now the primary one for servlets.

src/web/tntnet.xml
GET /admin.png or GET/MaterialXXX.png images are not delivered by tntnet static servlet. 
=> Problem : admin and Material images return vhost not found

src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp
Solution: Use HTTP error code 502 Bad Gateway.
*********************************************************************
This PR depends on https://github.com/42ity/fty-common-rest/pull/27 and https://github.com/42ity/fty-email/pull/70; first one is necessary for build.
=> (S/L) Problem: We have to change error behaviour of email_* REST API calls.

src/shared/configure_inform.cc
=> Problem: On UPS creation, list of UPSes for DC is not updated.

src/web/src/admin_passwd.ecpp.in
Solution: Additional content should be a variable
To that end, it should be a variable of TRANSLATE_ME calls
=> Problem: Invalid JSON is returned

src/web/src/add_gpio.ecpp
Solution: Use the right agent name
=> Problem: Typo in error message

src/web/src/sse.cc
Solution: Also forward inventory message
'inventory' messages complete the 'create' and 'update' messages previously sent
upon manual asset creation, adding the 'ext' attributes set. Conversely,
auto-discovered devices are already prepopulated with all the 'ext', which
explains the difference of behavior
Signed-off-by: Arnaud Quette <arnaud.quette@free.fr>
=> Problem: Manual asset creation doesn't well feed SSE

src/web/src/add_gpio.ecpp, src/web/src/alert_ack.ecpp, src/web/src/alert_rules.ecpp, src/web/src/asset_DELETE.ecpp, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/asset_actions_POST.ecpp, src/web/src/asset_import.ecpp, src/web/src/auth.ecpp, src/web/src/conf_scan.ecpp, src/web/src/config.ecpp, src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp, src/web/src/gpo_action.ecpp, src/web/src/http_proxy.ecpp, src/web/src/license_POST.ecpp, src/web/src/my_profile.ecpp, src/web/src/netcfg.ecpp, src/web/src/scan_run.ecpp, src/web/src/systemctl.ecpp, src/web/src/time.ecpp
Solution: add audit logging calls to show what user did (or didn't do)
Note: for review ignore whitespace changes
=> Problem: RestAPI calls are not auditable

src/web/src/asset_PUT.ecpp, src/web/src/conf_scan.ecpp, src/web/src/gpo_action.ecpp
We now fail the initial wizard due to the missed parenthesis (PR #661 diligently added a lot, missed one).
Also just in case this restores the "else" behavior in a couple of files for their successful outputs after some error-checking.
=> Fix audit logs after #661

src/web/src/asset_POST.ecpp
Another follow-up to #661 (and #663), broke our tests (and REST API clients) expecting a proper error for POSTing bad inputs.
=> asset_POST.ecpp : return a proper error message for bad input documents

src/web/src/add_gpio.ecpp, src/web/src/alert_ack.ecpp, src/web/src/alert_rules.ecpp, src/web/src/asset_DELETE.ecpp, src/web/src/asset_POST.ecpp, src/web/src/asset_PUT.ecpp, src/web/src/asset_actions_POST.ecpp, src/web/src/asset_import.ecpp, src/web/src/auth.ecpp, src/web/src/conf_scan.ecpp, src/web/src/config.ecpp, src/web/src/email_feedback.ecpp, src/web/src/email_test.ecpp, src/web/src/email_vote.ecpp, src/web/src/gpo_action.ecpp, src/web/src/http_proxy.ecpp, src/web/src/license_POST.ecpp, src/web/src/my_profile.ecpp, src/web/src/netcfg.ecpp, src/web/src/scan_run.ecpp, src/web/src/systemctl.ecpp, src/web/src/time.ecpp
This should provide necessary logs to get some idea about the auditing results.
This is dependant on https://github.com/42ity/fty-common-rest/pull/36 and won't pass until it is merged and updated on Jenkins/Travis
=> Added more audit logs

src/web/src/license_POST.ecpp
Solution: there may be a few reasons, like a re-POST of the license
request, to *why* this happens. The common solution is to wait for
the fty-db-ready file to exist.
Note: I was short on time writing this. A maybe better solution is to check file and services any time after we'd run the script and so not assume its (or mlm-subprocess) completion means something certain.
=> Problem: license_post proceeds even if db-init did not complete

src/web/src/systemctl.ecpp
Solution: secure the system back by using the wrapper script (via PATH envvar)
NOTE: Requires to be merged along with https://github.com/42ity/fty-core/pull/91 for REST API to still function
=> Problem: webserver and admin user allowed to call /bin/systemctl for anything

src/web/src/netcfg.ecpp
When updating DNS settings, they are put into dns-nameservers field of /etc/network/interfaces.
Then after network restart is finished, resolvconf picks them up, merges them with data from DHCP and puts everything into /etc/resolv.conf.
Before this change, both GET and PUT were reading DNS settings from /etc/resolv.conf. Because the network restart is asynchronous to PUT REST API call,
this meant that PUT might have return old DNS settings. Now we are returning the new settings even though they are not used before restart - that is
consistent with how we e.g. return new static IP address even though we are using old one until restart.
=> Make PUT netcfg return updated DNS settings.

src/web/src/current.ecpp
Solution: Serialize UPS outlets using the Outlets object
=> Problem: UPS do not use the Outlets object

src/web/src/current.ecpp
=> Problem: UPS outlets serialization is missing

src/web/src/config.ecpp
This is a refactoring of the /api/v1/admin/config REST endpoint, allowing the API to store arbitrary JSON objects and removing most hard-coded logic from the endpoint.
Due to unfortunate timing issues, there are a couple of points to address as soon as possible:
* lobby upstream czmq for marking zconfig_remove() as stable
* update 42ity's czmq with upstream's czmq
* remove local zconfig_remove() implementation hack
* split mapping data into separate files inside file-system
* prune dead code
This modification should be backwards-compatible.
=> Clean config REST endpoint

src/web/src/config.ecpp
Note: this is a modest clean-up of the config endpoint to get the error handling semantics right. The rest of the clean-up is still a post-release task.
=> Fix error handling of config endpoint

src/web/src/getlog_GET.ecpp
While updating CI tests for logs, I found that if a log file can not be found on the system (e.g. in a smaller-profile product build) then REST API returns the catch-all HTTP-500 error from this servlet:
````
500 Internal Server Error
Details:
{
"errors": [
{
"message": { "key": "Internal Server Error. {{var1}}", "variables": { "var1":  { "key": "Exception caught. Please check logs for more details." }  } },
"debug": "./src/web/src/getlog_GET.ecpp: 676",
"code": 42
}
]
}
````
This PR aims to detect if a valid `logname` was requested, and maps to a "real" file transferred as is, and report a failure to read it as HTTP-404.
This code avoids reporting HTTP-404 for "ALL" (a tarball of other types) and "journald" (exported from systemd), because these are generated and not backed by a …
=> "No log file" should return HTTP-404

src/web/src/license_POST.ecpp
It is neigh impossible to troubleshoot EULA problems when all the `POST .../license` related log entries have the same timestamp of when the processing has finished. This PR aims to rectify that.
=> Log eula acceptance progress with timestamps

src/web/src/getlog_GET.ecpp
The file is introduced by https://github.com/42ity/fty-core/pull/428
TODO: Perhaps test in CI that this call is not invalid (might return empty though)
=> getlog_GET.ecpp : serve the verify-fs log (see fty-core#428)

src/web/src/auth_verify.ecpp
* fix: if access_token is empty, continue with Anonymous user profile
**Note: here the api entries supporting Anonymous READ access**
src/web/src/conf_scan.ecpp:264
src/web/src/hw_capability.ecpp:122
src/web/src/info.ecpp:116
src/web/src/license_status.ecpp:41
src/web/src/license_text.ecpp:40
src/web/src/list_gpio.ecpp:167
src/web/src/scan_progress.ecpp:146
src/web/src/sysinfo.ecpp:703
=> IPMVAL-2889 - fix auth_verify.ecpp : restores behaviour with previous 42ity version

ecpp/average.ecpp, src/shared/utils.cc, zproject-hold/tests/shared/test-utils.cc
NOTE: TESTS DESACTIVATED FOR THIS PART. UNIT TESTS HAVE BEING DESACTIVATED DURING CMAKE MIGRATION ???
=> Fix bad initialization of variable in timegm function and add mutex 
